# Generated by Django 5.2.8 on 2025-12-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teammember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
    ]
